#if !defined(CONFIG_H)
#define CONFIG_H

#define FONT "Cascadia Mono:size=24"

#define STATUS_MARGIN_LEFT 5 // default: 3
#define STATUS_MARGIN_RIGHT 5 // default: 3
#define STATUS_ERROR_TEXT_COLOR (union sw_color){ 0xFFFF0000 }
#define STATUS_SEPARATOR_WIDTH 2

#define WORKSPACE_BORDER_WIDTH 1
#define WORKSPACE_MARGIN_LEFT 5
#define WORKSPACE_MARGIN_RIGHT 5
#define WORKSPACE_MARGIN_BOTTOM 1
#define WORKSPACE_MARGIN_TOP 1

#define BINDING_MODE_INDICATOR_BORDER_WIDTH 1
#define BINDING_MODE_INDICATOR_MARGIN_LEFT 5
#define BINDING_MODE_INDICATOR_MARGIN_RIGHT 5
#define BINDING_MODE_INDICATOR_MARGIN_BOTTOM 1
#define BINDING_MODE_INDICATOR_MARGIN_TOP 1

// ? TODO: TRAY_ICON_SIZE
#define TRAY_DBUSMENU_SEPARATOR_WIDTH 2
#define TRAY_DBUSMENU_CLOSE_AFTER_SELECTION 0 // default: 1

#endif // CONFIG_H
